### ISSUE TITLE
Multiple IDP's config

### ISSUE THREAD

**Issue by manojvings** [grafana/django-saml2-auth#104]
There is no proper documentation that says multiple IDP's are supported. For ex: if we want to support google as IDP and amazon as another IDP, how do we configure both the metadata xml in django with this library?

**Comment by mostafa** [comment]
Hey @manojvings,

You can use the `TRIGGER.GET_METADATA_AUTO_CONF_URLS` hook function to generate a list of metadata autoconf URLs, this way you can have multi-tenancy. The function should return a `Optional[List[Dict[str, str]]]`:
```python
[{"url": "https://<idp-url.tld>/sso/saml/metadata"}, ...]
```

**Comment by manojvings** [comment]
Is it possible to store the multiple metadata locally as xml and configure instead of urls?

**Comment by mostafa** [comment]
@manojvings 
The current implementation wouldn't allow that, but you can store files on object storage buckets and pass the URL. You might be able to use the [`file:///` URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme) to achieve that, but I haven't tested it. Let me know if it works for you, so I can add more tests.

**Comment by manojvings** [comment]
> Hey @manojvings,
> 
> You can use the `TRIGGER.GET_METADATA_AUTO_CONF_URLS` hook function to generate a list of metadata autoconf URLs, this way you can have multi-tenancy. The function should return a `Optional[List[Dict[str, str]]]`:
> 
> ```python
> [{"url": "https://<idp-url.tld>/sso/saml/metadata"}, ...]
> ```

After configuring this, i was trying to test this out but to no avail. Configured url1 and url2. Individually it works fine but if i configure both the urls together, its failing. May be i am not testing the right way? On seeing the multiple urls, what will be the behaviour of this library? will it ask to choose one url/provider to authenticate? How to test this out?

**Comment by mostafa** [comment]
@manojvings It checks the signature against all the available certificates in the metadata files and when it matches one, it stops checking others. Check the tests and the usage of [this fixture](https://github.com/grafana/django-saml2-auth/blob/0514baa9dd57c89114df2837788884bb5bbdd8b2/django_saml2_auth/tests/test_saml.py#L84) to see how it works.
