### ISSUE TITLE
Understanding sp-initiated process

### ISSUE THREAD

**Issue by heydonovan** [grafana/django-saml2-auth#105]
I've an app working just fine with IdP-initiated login. However, the app is behind a proxy and doesn't replay the POST request from the IdP. It simply issues a GET request for the same URL (`domain.com/sso/acs`) after authentication. This causes us to have to refresh twice, in order to authenticate with the proxy, and then go through the IdP process again.

To work around this, I figure if I can get the app to redirect to our IdP with a GET request, I'd be good. If I navigate to `domain.com/sso/sp/`, I seem to get denied. I've played around with the `USE_JWT` setting, but we don't use JWT for user authentication so I don't think this is the right path. The code for `sp_initiated_login` seems to require a token, so maybe JWT has to be used? Is there a way to check if you're logged in, and if not, redirect you to your IdP? I'm passing in a `RelayState` from our IdP in hopes of it redirecting me, but don't think that is right either.

**Comment by mostafa** [comment]
Hey @heydonovan,

The SP-initiated SAML SSO is a bit opinionated, but this is the flow. Steps 1~3 is done in your backend, and the rest are done in `django-saml2-auth`.
1. Receive the user's email from your frontend and validate it as usual (in your Django views/endpoints).
2. Create a JWT with the email in it (in Django). The token should contain an extra field to prevent reuse in the `sp_initiated_login` endpoint.
3. Pass the JWT and the redirect URL to the frontend. Alternatively you can force redirect the user from backend. The redirect URL is a combination of the assertion URL plus the SP endpoint, which is something like `https://url/.../sp?token=JWT`:
```python
assertion_url = settings.SAML2_AUTH.get("ASSERTION_URL")
redirect_url = urljoin(assertion_url, reverse("django_saml2_auth:sp"))
```
4. Receive the JWT token back in the redirect URL in the `sp_initiated_login` endpoint. The JWT created in this endpoint doesn't contain the extra field.
5. Create a SAML `authn_request` and redirect the user from there with a new refreshed JWT token in step 4.
6. The rest is the same as the IdP-initiated flow from the `acs` endpoint.

**Comment by bogdan-calapod** [comment]
Hey, sorry for bringing this up again but I'm trying to integrate this into a Django app which I want to serve as an IdP and am having a bit of trouble.

We are using Django and DRF as the API for a React SPA. From my understanding, the flow would be:

1. The SP makes the SAML request and redirects to `https://my.idp/sso/welcome/`
2. The IdP redirects to the login page, containing the `SAMLRequest` query parameter
3. The frontend does the login request and then calls `https://my.idp/sso/sp?token=JWT`
4. Backend (or frontend) redirects to `https://my.idp/sso/assertionUrl?SAMLRequest=...&token=JWT` which creates the SAML auth request 
5. User gets redirected to SP with the authentication request ? 

I'm pretty sure I'm missing something really obvious here but for the life of me I can't see what :/

Thank you btw for this library, it seems like it's the only SAML library for Django which is still being updated

**Comment by mostafa** [comment]
Hey @bogdan-calapod,

This library is not designed to make Django act as an IdP. The SP is your Django app and the IdP will be Okta or any other SAML-enabled IdP. Note that, for SP to work, the user must have already existed in your system, otherwise it'd be very hard to find out who belongs to which company, group or project.

**Comment by bogdan-calapod** [comment]
Ah, so *that's* what I missed - thank you. This bit in the readme got me a bit confused:

> This plugin supports both identity provider and service provider-initiated SSO:
>
>    For IdP-initiated SSO, the user should sign in to their identity provider platform, e.g., Okta, and click on the application that authorizes and redirects the user to the service provider, that is your platform.
>    For SP-initiated SSO, the user should first exist on your platform, either by signing in via the first method (IdP-initiated SSO) or any other custom solution. It can be configured to be redirected to the correct application on the identity provider platform.

But I guess Django would be the `SP` in both of these cases, right ? So if I want Django to act as an IdP I'd need to use something like `djangosaml2idp`
