### ISSUE TITLE
How difficult is it to migrate from fangli/django-saml2-auth?

### ISSUE THREAD

**Issue by redwitchproject** [grafana/django-saml2-auth#106]
Are there some instructions on how to migrate from https://github.com/fangli/django-saml2-auth to this fork?

**Comment by mostafa** [comment]
Hey @redwitchproject,

There are no migration instructions as of now. but for setup instructions, you can have a look at the README's [How to Use](https://github.com/grafana/django-saml2-auth#how-to-use) section. The setup instructions are roughly the same and I heavily updated the README and added a lot of information about each individual setting parameter.

Feel free to ask specific questions if you have any.

**Comment by anowerym** [comment]
We only had to add `ALLOWED_REDIRECT_HOSTS` to the `SAML2_AUTH`-settings. However, we currently run into [Issue 109](https://github.com/grafana/django-saml2-auth/issues/109).
