### ISSUE TITLE
Package appears to be broken

### ISSUE THREAD

**Issue by michaelsteigman** [grafana/django-saml2-auth#109]
Opening a new issue around the reports at the bottom of #25. The issues reported by all of those users is different than the issue the OP reported.

To summarize, with everything configured on the Okta/IdP side (signing turned on, etc.) and the METADATA_AUTO_CONF_URL set, the login process breaks when Pysaml tries to sign the request using xmlsec without a private key. The `com_list` in my case looks like

```
['/usr/local/bin/xmlsec1', '--sign', '--privkey-pem', None, '--id-attr:ID', 'urn:oasis:names:tc:SAML:2.0:protocol:AuthnRequest', '--node-id', 'id-DfHiSpJb952UZTS0G']
```

The last call is below -`_runxmlsec` in the Pysaml module. The exception generated by this mis-configuration is not an `XmlsecError` so it's uncaught.

https://github.com/IdentityPython/pysaml2/blob/4fa20a92a9d7fccc2ca34f1f6ad777cc0fd36ef7/src/saml2/sigver.py#L783

The actual error is
`TypeError: sequence item 3: expected str instance, NoneType found error`

And all I see in the log is
```
Internal Server Error: /accounts/login/
Internal Server Error: /accounts/login/
```

I have spent some tracking the code path and context at each step and don't see where the private key could possibly be populated from. That, along with the reports from other users on the same error leads me to believe that the package is broken at the moment.  I don't have experience with the package however and would be happy to be proven wrong.

**Comment by mostafa** [comment]
Hey @michaelsteigman,

This package doesn't support assertion encryption for now, but I'd be happy to see contributions. The support is already available, thanks to pysaml2, but the django-saml2-auth should have a way to pass down the keys and secrets to the pysaml2 library, which it doesn't at the moment. The configuration options are documented here:
- https://pysaml2.readthedocs.io/en/latest/howto/config.html
- https://pysaml2.readthedocs.io/en/latest/howto/config.html#key-file
- https://pysaml2.readthedocs.io/en/latest/howto/config.html#cert-file
- https://pysaml2.readthedocs.io/en/latest/howto/config.html#verify-ssl-cert

**Comment by michaelsteigman** [comment]
Thanks for the response, @mostafa.

I must be missing something. I did not ask for the assertion to be encrypted. (Nor I'd guess are the posters reporting the same issue on #25). If I was, this error would make some sense.

I am just trying to get a basic integration going with Okta via SAML.

What do I need to do to turn off assertion encryption?

**Comment by mostafa** [comment]
@michaelsteigman You need to turn it off on the Okta app you created.

**Comment by michaelsteigman** [comment]
@mostafa Unfortunately, that is not the issue. That setting was set to unencrypted. See the advanced settings below.

![Screen Shot 2022-11-11 at 8 48 31 AM](https://user-images.githubusercontent.com/1427572/201433373-fcb7f0b4-8059-42c4-ba12-103a2460d17f.png)

Also tried setting assertions to unsigned but still see the error

`TypeError: sequence item 3: expected str instance, NoneType found error`

Other suggestions?

**Comment by mostafa** [comment]
@michaelsteigman Can you confirm this?
https://github.com/grafana/django-saml2-auth/issues/25#issuecomment-1313358044
