### ISSUE TITLE
Extract metadata file/URL with django-saml2-auth

### ISSUE THREAD

**Issue by chiavariniluca** [grafana/django-saml2-auth#158]
I have a Python-Django project and I'm trying to integrate with a C#/.NET existing website SAML authentication, using their idp.
I absolutely need to generate a metadata file to give to whoever manages the IdP (C#/.NET website) to implement SSO.
How can I implement it?

**Comment by AssenDimitrov** [comment]
Seems like its not working at the moment, we have to fix it ourselves :)

**Comment by mostafa** [comment]
@chiavariniluca @AssenDimitrov 
Can you elaborate? AFAIK, you don't generate the metadata file, rather it is what the IdP does. You, using this library, consume the metadata file. This means that you cannot use this library to create a SAML authentication server.

**Comment by AssenDimitrov** [comment]
AFAIK ENTITI_ID is the local app url which should give some data/metadata in return to bound with iDP.
