### ISSUE TITLE
Inefficient metadata URL validation

### ISSUE THREAD

**Issue by Otrebus-EL** [grafana/django-saml2-auth#166]
When validating a metadata url [here](https://github.com/grafana/django-saml2-auth/blob/72b2d5084f612cce8050c4d8df0ecc826a16d5cc/django_saml2_auth/saml.py#L68) it's done by performing a GET request against the URL. This adds quite a bit of delay in the authentication process since if I have several metadata urls in my `GET_METADATA_AUTO_CONF_URLS` each of them will first be fetched by django-saml2-auth and then actually fetched by saml2.

**Comment by mostafa** [comment]
Hey @Otrebus-EL,

TLDR,
You can solve this issue by using [`GET_USER_ID_FROM_SAML_RESPONSE` trigger](https://github.com/grafana/django-saml2-auth/blob/6b3d05460f24e3b213f560ede0ce4ede975ca66f/django_saml2_auth/saml.py#L164-L167), which is executed before the `GET_METADATA_AUTO_CONF_URLS` trigger.

Longer version:
You can read more about multi-tenancy [here](https://github.com/grafana/django-saml2-auth/issues/169#issuecomment-1527556259).
