### ISSUE TITLE
Slashes in SAML2 attribute names don't work

### ISSUE THREAD

**Issue by Otrebus-EL** [grafana/django-saml2-auth#167]
If an attribute name contains slashes (like they often do if they follow the claim uri format like e.g. "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress") then [this code](https://github.com/grafana/django-saml2-auth/blob/6b3d05460f24e3b213f560ede0ce4ede975ca66f/django_saml2_auth/saml.py#L342) fails since the slashes in the url are interpreted as dictor path separators.

**Comment by mostafa** [comment]
Hey @Otrebus-EL,

the code expects the attributes to be pure and without namespaces, which is why this happens, and you already pointed it out. Do you have any idea how to solve it? If so, please make a PR and I'll review it.
