### ISSUE TITLE
Why is the token attribute mandatory?

### ISSUE THREAD

**Issue by jean-sh** [grafana/django-saml2-auth#20]
I'm noticing the `token` attribute in `ATTRIBUTES_MAP` is mandatory and an error is raised if it's not specified, why is that? What is it used for? I can't find it in django-saml2-auth, pysaml2 or Django...

**Comment by jean-sh** [comment]
Does anyone know? I tried supplying some dummy token value ("12345") and it seems to work, but I still don't know what it is for, or if it's a security concern.

**Comment by mostafa** [comment]
Hey @jean-sh,

It's an implementation detail of our own system, but since we needed it, I included it in the code.

**Comment by JVemmer** [comment]
> Hey @jean-sh,
> 
> It's an implementation detail of our own system, but since we needed it, I included it in the code.

It seems odd to add an attribute, and making it mandatory, if it is an attribute unique to your system; unless this projekt is not meant to be a widely used implementation of django-saml2-auth, and is rather just a project used solely for your systems, in which case I think a big disclaimer on the repository would be nice.
At the very least, it would be nice with some documentation regarding the attribute, or rather the use in your systems, so others may draw inspiration from it.

**Comment by mostafa** [comment]
@JVemmer Fair enough! I see what I can do.

**Comment by mostafa** [comment]
@JVemmer @jean-sh Please review the PR #23! 🙏

**Comment by mostafa** [comment]
@JVemmer @jean-sh I merged the feature PR.
