### ISSUE TITLE
Sorry, you are not allowed to access this app To report a problem with your access please contact your system administrator

### ISSUE THREAD

**Issue by Pavithra098765** [grafana/django-saml2-auth#205]
Hi, I'm facing this error when login http://localhost/accounts/login/

This is my uls.py
from django.contrib import admin
from django.urls import path, include
import django_saml2_auth.views

urlpatterns = [
path('admin/', admin.site.urls),
path(r'saml2_auth/', include('django_saml2_auth.urls')),
path(r'accounts/login/', django_saml2_auth.views.signin),
path(r'admin/login/', django_saml2_auth.views.signin),
]

I have added keycloak url in my settings.py

'METADATA_AUTO_CONF_URL': 'https://localhost:8443/auth/realms/NOC/protocol/saml/descriptor',
Please help to fix this

**Comment by mostafa** [comment]
@Pavithra098765 

I'd be happy to help you fix this problem, but please provide more information, like your configuration, your app settings and any related information. Also, consider trying the debugging technique, tools and configuration explained in the [how to debug?](https://github.com/grafana/django-saml2-auth#how-to-debug) section.

**Comment by Pavithra098765** [comment]
Hi @mostafa

I have done all changes that are mentioned in the artical.
And i have check saml-tracker that indicated internal server error 500.

django_saml2_auth is my app. Please find the below app files.And help me 

App/url.py
                                                         
from django.conf.urls import url
from . import views

app_name = 'django_saml2_auth'

urlpatterns = [
    url(r'^acs/$', views.acs, name="acs"),
    url(r'^welcome/$', views.welcome, name="welcome"),
    url(r'^denied/$', views.denied, name="denied"),
]

App/views.py
import os, django
#from users.models import UserModel
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "/home/vvdnadmin/sso/noc/noc/settings.py")
#django.setup()

from saml2 import (
    BINDING_HTTP_POST,
    BINDING_HTTP_REDIRECT,
    entity,
)
from saml2.client import Saml2Client
from saml2.config import Config as Saml2Config

from django import get_version
from pkg_resources import parse_version
from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, get_user_model
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.template import TemplateDoesNotExist
from django.http import HttpResponseRedirect
from django.utils.http import is_safe_url

from rest_auth.utils import jwt_encode

# default User or custom User. Now both will work.
User = get_user_model()
try:
    import urllib2 as _urllib
except:
    import urllib.request as _urllib
    import urllib.error
    import urllib.parse

if parse_version(get_version()) >= parse_version('1.7'):
    from django.utils.module_loading import import_string
else:
    from django.utils.module_loading import import_by_path as import_string


def _default_next_url():
    if 'DEFAULT_NEXT_URL' in settings.SAML2_AUTH:
        return settings.SAML2_AUTH['DEFAULT_NEXT_URL']
    # Lazily evaluate this in case we don't have admin loaded.
    return get_reverse('admin:index')


def get_current_domain(r):
    if 'ASSERTION_URL' in settings.SAML2_AUTH:
        return settings.SAML2_AUTH['ASSERTION_URL']
    return '{scheme}://{host}'.format(
        scheme='https' if r.is_secure() else 'http',
        host=r.get_host(),
    )


def get_reverse(objs):
    '''In order to support different django version, I have to do this '''
    if parse_version(get_version()) >= parse_version('2.0'):
    from django.urls import reverse
    else:
        from django.core.urlresolvers import reverse
    if objs.__class__.__name__ not in ['list', 'tuple']:
        objs = [objs]

    for obj in objs:
        try:
            return reverse(obj)
        except:
            pass
    raise Exception('We got a URL reverse issue: %s. This is a known issue but please still submit a ticket at https://github.com/fangli/djan>


def _get_metadata():
    if 'METADATA_LOCAL_FILE_PATH' in settings.SAML2_AUTH:
        return {
            'local': [settings.SAML2_AUTH['METADATA_LOCAL_FILE_PATH']]
        }
    else:
        return {
            'remote': [
                {
                    "url": settings.SAML2_AUTH['METADATA_AUTO_CONF_URL'],
                },
            ]
        }


def _get_saml_client(domain):
    acs_url = domain + get_reverse([acs, 'acs', 'django_saml2_auth:acs'])
    metadata = _get_metadata()
 saml_settings = {
        'metadata': metadata,
        'service': {
            'sp': {
                'endpoints': {
                    'assertion_consumer_service': [
                        (acs_url, BINDING_HTTP_REDIRECT),
                        (acs_url, BINDING_HTTP_POST)
                    ],
                },
                'allow_unsolicited': True,
                'authn_requests_signed': False,
                'logout_requests_signed': True,
                'want_assertions_signed': True,
                'want_response_signed': False,
            },
        },
    }

    if 'ENTITY_ID' in settings.SAML2_AUTH:
        saml_settings['entityid'] = settings.SAML2_AUTH['ENTITY_ID']

    if 'NAME_ID_FORMAT' in settings.SAML2_AUTH:
        saml_settings['service']['sp']['name_id_format'] = settings.SAML2_AUTH['NAME_ID_FORMAT']

    spConfig = Saml2Config()
    spConfig.load(saml_settings)
    spConfig.allow_unknown_attributes = True
    saml_client = Saml2Client(config=spConfig)
    return saml_client
@login_required
def welcome(r):
    try:
        return render(r, 'django_saml2_auth/welcome.html', {'user': r.user})
    except TemplateDoesNotExist:
        return HttpResponseRedirect(_default_next_url())


def denied(r):
    return render(r, 'django_saml2_auth/denied.html')


def _create_new_user(username, email, firstname, lastname):
    user = User.objects.create_user(username, email)
    user.first_name = firstname
    user.last_name = lastname
    groups = [Group.objects.get(name=x) for x in settings.SAML2_AUTH.get('NEW_USER_PROFILE', {}).get('USER_GROUPS', [])]
    if parse_version(get_version()) >= parse_version('2.0'):
        user.groups.set(groups)
    else:
        user.groups = groups
    user.is_active = settings.SAML2_AUTH.get('NEW_USER_PROFILE', {}).get('ACTIVE_STATUS', True)
    user.is_staff = settings.SAML2_AUTH.get('NEW_USER_PROFILE', {}).get('STAFF_STATUS', True)
    user.is_superuser = settings.SAML2_AUTH.get('NEW_USER_PROFILE', {}).get('SUPERUSER_STATUS', False)
    user.save()
    return user


@csrf_exempt
def acs(r):
    saml_client = _get_saml_client(get_current_domain(r))
  GNU nano 4.8                                              django_saml2_auth/views.py                                              Modified  
    resp = r.POST.get('SAMLResponse', None)
    next_url = r.session.get('login_next_url', _default_next_url())

    if not resp:
        return HttpResponseRedirect(get_reverse([denied, 'denied', 'django_saml2_auth:denied']))

    authn_response = saml_client.parse_authn_request_response(
        resp, entity.BINDING_HTTP_POST)
    if authn_response is None:
        return HttpResponseRedirect(get_reverse([denied, 'denied', 'django_saml2_auth:denied']))

    user_identity = authn_response.get_identity()
    print (user_identity)
    if user_identity is None:
        return HttpResponseRedirect(get_reverse([denied, 'denied', 'django_saml2_auth:denied']))

    user_email = user_identity[settings.SAML2_AUTH.get('ATTRIBUTES_MAP', {}).get('email', 'Email')][0]
    user_name = user_identity[settings.SAML2_AUTH.get('ATTRIBUTES_MAP', {}).get('username', 'UserName')][0]
    user_first_name = user_identity[settings.SAML2_AUTH.get('ATTRIBUTES_MAP', {}).get('first_name', 'FirstName')][0]
    user_last_name = user_identity[settings.SAML2_AUTH.get('ATTRIBUTES_MAP', {}).get('last_name', 'LastName')][0]

    target_user = None
    is_new_user = False
    try:
        target_user = User.objects.get(username=user_name)
        if settings.SAML2_AUTH.get('TRIGGER', {}).get('BEFORE_LOGIN', None):
            import_string(settings.SAML2_AUTH['TRIGGER']['BEFORE_LOGIN'])(user_identity)
    except User.DoesNotExist:
        new_user_should_be_created = settings.SAML2_AUTH.get('CREATE_USER', True)
        if new_user_should_be_created: 
            target_user = _create_new_user(user_name, user_email, user_first_name, user_last_name)
            if settings.SAML2_AUTH.get('TRIGGER', {}).get('CREATE_USER', None):
  import_string(settings.SAML2_AUTH['TRIGGER']['CREATE_USER'])(user_identity)
            is_new_user = True
        else:
            return HttpResponseRedirect(get_reverse([denied, 'denied', 'django_saml2_auth:denied']))

    r.session.flush()

    if target_user.is_active:
        target_user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(r, target_user)
    else:
        return HttpResponseRedirect(get_reverse([denied, 'denied', 'django_saml2_auth:denied']))

    if settings.SAML2_AUTH.get('USE_JWT') is True:
        # We use JWT auth send token to frontend
        jwt_token = jwt_encode(target_user)
        query = '?uid={}&token={}'.format(target_user.id, jwt_token)

        frontend_url = settings.SAML2_AUTH.get(
            'FRONTEND_URL', next_url)

        return HttpResponseRedirect(frontend_url+query)

    if is_new_user:
        try:
            return render(r, 'django_saml2_auth/welcome.html', {'user': r.user})
        except TemplateDoesNotExist:
            return HttpResponseRedirect(next_url)
    else:
        return HttpResponseRedirect(next_url)

def signin(r):
    try:
        import urlparse as _urlparse
        from urllib import unquote
    except:
        import urllib.parse as _urlparse
        from urllib.parse import unquote
    next_url = r.GET.get('next', _default_next_url())

    try:
        if 'next=' in unquote(next_url):
            next_url = _urlparse.parse_qs(_urlparse.urlparse(unquote(next_url)).query)['next'][0]
    except:
        next_url = r.GET.get('next', _default_next_url())

    # Only permit signin requests where the next_url is a safe URL
    if parse_version(get_version()) >= parse_version('2.0'):
        url_ok = is_safe_url(next_url, None)
    else:
        url_ok = is_safe_url(next_url)

    if not url_ok:
        return HttpResponseRedirect(get_reverse([denied, 'denied', 'django_saml2_auth:denied']))

    r.session['login_next_url'] = next_url

    saml_client = _get_saml_client(get_current_domain(r))
    _, info = saml_client.prepare_for_authenticate()

    redirect_url = None

    for key, value in info['headers']:
   if key == 'Location':
            redirect_url = value
            break

    return HttpResponseRedirect(redirect_url)


def signout(r):
    logout(r)
    return render(r, 'django_saml2_auth/signout.html')

**Comment by mostafa** [comment]
Hey @Pavithra098765,

What you provided is neither your configuration nor your hook functions. As far as I looked, this is the same code you copy-pasted from the current library. This is not helpful at all in your case.

**Comment by Pavithra098765** [comment]
Hi @mostafa 

Please let me know what kind of information you need,I configure the above things only.

**Comment by mostafa** [comment]
@Pavithra098765 

1. What is your `SAML_AUTH` configuration? I am referring to point No. 4 in [this link](https://github.com/grafana/django-saml2-auth#how-to-use).
2. Are you using an autoconf URL and setting the `METADATA_AUTO_CONF_URL` config parameter?
3. Is your application multi-tenant? What is the function you wrote to set the `TRIGGER.GET_METADATA_AUTO_CONF_URLS`?
4. Did you set the rest of the configuration parameters correctly?
5. Which Identity Provider do you use? And what is the configuration of your SSO app?
6. Are you using encryption? If so, are you setting the `KEY_FILE` and the `CERT_FILE`?
7. Are you using JWT? If so, how? And which algorithm do you use?

All the questions are derived from question 1 and you provided none. This library works by properly configuring the IdP app (like Okta) and your own Django application. The [README](https://github.com/grafana/django-saml2-auth/blob/main/README.md) contains all the relevant information you need to configure your Django app. And your IdP should provide their own documentation on how to set up a new SAML SSO application on their platform.

**Comment by PrabhuBose** [comment]
Hi @mostafa,

I am having the same issue. I am having problem in configuring SAML2_AUTH. Can you please help me. Below are my SAML2_AUTH configuration. I am trying with FusionAuth IDP.

`SAML2_AUTH = {
    # Metadata is required, choose either remote url or local file path
    'METADATA_AUTO_CONF_URL': 'http://localhost:9011/samlv2/metadata/d7d09513-a3f5-401c-9685-34ab6c552453',
    # 'METADATA_LOCAL_FILE_PATH': '[The metadata configuration file path]',
    'KEY_FILE': '[The key file path]',
    'CERT_FILE': '[The certificate file path]',

    # If both `KEY_FILE` and `CERT_FILE` are provided, `ENCRYPTION_KEYPAIRS` will be added automatically. There is no need to provide it unless you wish to override the default value.
    'ENCRYPTION_KEYPAIRS': [
        {
            "key_file": '[The key file path]',
            "cert_file": '[The certificate file path]',
        }
    ],

    'DEBUG': False,  # Send debug information to a log file
    # Optional logging configuration.
    # By default, it won't log anything.
    # The following configuration is an example of how to configure the logger,
    # which can be used together with the DEBUG option above. Please note that
    # the logger configuration follows the Python's logging configuration schema:
    # https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
    'LOGGING': {
        'version': 1,
        'formatters': {
            'simple': {
                'format': '[%(asctime)s] [%(levelname)s] [%(name)s.%(funcName)s] %(message)s',
            },
        },
        'handlers': {
            'stdout': {
                'class': 'logging.StreamHandler',
                'stream': 'ext://sys.stdout',
                'level': 'DEBUG',
                'formatter': 'simple',
            },
        },
        'loggers': {
            'saml2': {
                'level': 'DEBUG'
            },
        },
        'root': {
            'level': 'DEBUG',
            'handlers': [
                'stdout',
            ],
        },
    },

    # Optional settings below
    'DEFAULT_NEXT_URL': '/admin',
    # Custom target redirect URL after the user get logged in. Default to /admin if not set. This setting will be overwritten if you have parameter ?next= specificed in the login URL.
    'CREATE_USER': True,  # Create a new Django user when a new user logs in. Defaults to True.
    'NEW_USER_PROFILE': {
        'USER_GROUPS': [],  # The default group name when a new user logs in
        'ACTIVE_STATUS': True,  # The default active status for new users
        'STAFF_STATUS': False,  # The staff status for new users
        'SUPERUSER_STATUS': False,  # The superuser status for new users
    },
    'ATTRIBUTES_MAP': {  # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
        'email': 'richard@example.com',
        'username': 'user.username',
        'first_name': 'user.first_name',
        'last_name': 'user.last_name',
        'token': 'Token',  # Mandatory, can be unrequired if TOKEN_REQUIRED is False
        'groups': 'Groups',  # Optional
    },
    'GROUPS_MAP': {  # Optionally allow mapping SAML2 Groups to Django Groups
        'SAML Group Name': 'Django Group Name',
    },
    'TRIGGER': {
        # Optional: needs to return a User Model instance or None
        'GET_USER': 'path.to.your.get.user.hook.method',
        'CREATE_USER': 'path.to.your.new.user.hook.method',
        'BEFORE_LOGIN': 'path.to.your.login.hook.method',
        'AFTER_LOGIN': 'path.to.your.after.login.hook.method',
        # Optional. This is executed right before METADATA_AUTO_CONF_URL.
        # For systems with many metadata files registered allows to narrow the search scope.
        'GET_USER_ID_FROM_SAML_RESPONSE': 'path.to.your.get.user.from.saml.hook.method',
        # This can override the METADATA_AUTO_CONF_URL to enumerate all existing metadata autoconf URLs
        'GET_METADATA_AUTO_CONF_URLS': 'path.to.your.get.metadata.conf.hook.method',
    },
    'ASSERTION_URL': 'http://localhost:9011/',  # Custom URL to validate incoming SAML requests against
    'ENTITY_ID': 'http://localhost:9011/saml2_auth/acs/',  # Populates the Issuer element in authn request
    # 'NAME_ID_FORMAT': user.email,  # Sets the Format property of authn NameIDPolicy element, e.g. 'user.email'
    'USE_JWT': True,
    # Set this to True if you are running a Single Page Application (SPA) with Django Rest Framework (DRF), and are using JWT authentication to authorize client users
    'JWT_ALGORITHM': 'HS256',  # JWT algorithm to sign the message with
    'JWT_SECRET': 'your.jwt.secret',  # JWT secret to sign the message with
    'JWT_PRIVATE_KEY': '--- YOUR PRIVATE KEY ---',
    # Private key to sign the message with. The algorithm should be set to RSA256 or a more secure alternative.
    'JWT_PRIVATE_KEY_PASSPHRASE': 'your.passphrase',
    # If your private key is encrypted, you might need to provide a passphrase for decryption
    'JWT_PUBLIC_KEY': '--- YOUR PUBLIC KEY ---',  # Public key to decode the signed JWT token
    'JWT_EXP': 60,  # JWT expiry time in seconds
    'FRONTEND_URL': 'http://localhost:8000/',
    # Redirect URL for the client if you are using JWT auth with DRF. See explanation below
    'LOGIN_CASE_SENSITIVE': True,  # whether of not to get the user in case_sentive mode
    'AUTHN_REQUESTS_SIGNED': True,  # Require each authentication request to be signed
    'LOGOUT_REQUESTS_SIGNED': True,  # Require each logout request to be signed
    'WANT_ASSERTIONS_SIGNED': True,  # Require each assertion to be signed
    'WANT_RESPONSE_SIGNED': True,  # Require response to be signed
    'ACCEPTED_TIME_DIFF': None,  # Accepted time difference between your server and the Identity Provider
    'ALLOWED_REDIRECT_HOSTS': ["http://localhost:8000/"],
    # Allowed hosts to redirect to using the ?next parameter
    'TOKEN_REQUIRED': False,  # Whether or not to require the token parameter in the SAML assertion
}`
