### ISSUE TITLE
Question: Encrypted Assertion not unencrypting 

### ISSUE THREAD

**Issue by charleslstone** [grafana/django-saml2-auth#223]
Having spent many hours on this, I am asking for your help.
IDP is a wordpress site using a mini-Orange plugin for SSO  SAML.  User logs into this wordpress site, clicks a button, and is transferred via SSO to my django site where user is auto-logged in using django-saml2-auth.

This works fine with a signed Assertion/Request (with SAML2_AUTH.CERT_FILE pointed to the mini-Orange public key file and Encrypted Assertion not enabled.

However, when I enable Encrypted Assertion and provide mini-Orange my openSSL public key and point SAML2_AUTH.KEY_FILE to my private_key.pem, it seems that the decryption (and login) fails with Error Code 1110.

I have separately confirmed the private and public keys match by checking the modulus of each:
openssl rsa -noout -modulus -in private_key.pem | openssl sha256

final debug output is:  
[2023-11-22 19:50:36,103] [DEBUG] [saml2.response.parse_assertion] ***Encrypted assertion/-s***
[2023-11-22 19:50:36,104] [DEBUG] [saml2.response.parse_assertion] --- AVA: {}
[2023-11-22 19:50:36,104] [DEBUG] [django_saml2_auth.utils.handle_exception] No name_id in SAML response.

At this point, I am at a loss about what to do next to get Encrypted Assertion working.   Any suggestions / help will be greatly appreciated.

    'KEY_FILE': os.path.join(CERT_DIR, 'private_key.pem'),
    'CERT_FILE': os.path.join(CERT_DIR, 'idp-signing.crt'),

    # Require each authentication request to be signed
    'AUTHN_REQUESTS_SIGNED': False,
    # Require each assertion to be signed
    'WANT_ASSERTIONS_SIGNED': True,
    # Require response to be signed
    'WANT_RESPONSE_SIGNED': False,
    # Require each logout request to be signed
    'LOGOUT_REQUESTS_SIGNED': False,
    'TOKEN_REQUIRED': False,

**Comment by charleslstone** [comment]
I still have not solved this. Any assistance will be much appreciated. Thanks.

**Comment by benmcelyea** [comment]
It looks like the error you are getting is "_No name_id in SAML response_". That also corresponds to Error Code 1110. Have you verified that the IDP is sending the name_id using a SAML tracer? What do you have your 'NAME_ID_FORMAT' set too? 

This is the code check you are likely failing. Its in the saml.py file in the library. You can try commenting it out and seeing if that fixes your problem:

  ```
  if not authn_response.name_id:
        raise SAMLAuthError("No name_id in SAML response.", extra={
            "exc_type": ValueError,
            "error_code": NO_NAME_ID_IN_SAML_RESPONSE,
            "reason": "There was an error processing your request.",
            "status_code": 500
        })
```

**Comment by charleslstone** [comment]
Thank you for getting back to me.  The SSO works fine as long as I do not have Encrypted Assertion enabled.  With DEBUG = True, I could see the name_id attribute in the response and its coming thru to my authentication code.  

I have:  'NAME_ID_FORMAT': 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',

It is tricky for me to comment out lines since this code is deployed using a docker image that auto-builds using requirements.txt file.  My workaround is to re-direct the IDP URL to point to my dev machine via an NGROK url so I can test it locally and there I can comment out the code you suggested.  I will do this tomorrow.

Thanks again,
Charlie
