### ISSUE TITLE
Help locating sp metadata URL to provide to Idp

### ISSUE THREAD

**Issue by nicolecurrens** [grafana/django-saml2-auth#226]
This is my first time working on a SAML integration and I'm a bit confused. We need to provide an sp metadata URL to our Idp and we can't figure it out. I'm running my django application locally.

In my urls.py, I have
`import django_saml2_auth.views`

and 
```
urlpatterns = [
 re_path(r'^sso/', include('django_saml2_auth.urls')),
...
]
```

In settings, I have
```
INSTALLED_APPS = [
    '...',
    'django_saml2_auth',
]
```

And

```
SAML2_AUTH = {
    # Metadata is required, choose either remote url or local file path
    'METADATA_AUTO_CONF_URL': <Our URL>,
    'ENTITY_ID': 'http://django:8000/sso/sp',
}
```

When I go to any of the URLs (ex. /sso/sp), I get the permission denied page. We haven't set up the SAML integration with our provider yet because they need the sp metadata URL before they can set up things on their end. Can someone let me know where to find this URL? All the views in the app seem to require the SAML integration to already be set up.

**Comment by mostafa** [comment]
Hey @nicolecurrens,

It is the identity provider that provides you with a metadata URL. This library cannot act as an identity provider.
