### ISSUE TITLE
CUSTOM_CREATE_JWT and CUSTOM_TOKEN_QUERY have different tokens.

### ISSUE THREAD

**Issue by Nodees** [grafana/django-saml2-auth#272]
I need the token from the CUSTOM_CREATE_JWT trigger and the CUSTOM_TOKEN_QUERY trigger to be the same. However, in the first trigger, I have the token with JTI "123", and in the CUSTOM_TOKEN_QUERY trigger, the token is "124".

**Comment by mostafa** [comment]
Hey @Nodees,

Can you elaborate with a code snippet?

**Comment by Nodees** [comment]
I identified the problem, thank you very much for the answer, everything is now resolved 😄

**Comment by mostafa** [comment]
Feel free to leave a comment for others that might bump into the same problem.
