### ISSUE TITLE
Exception handling not reading the value of `DEBUG` setting

### ISSUE THREAD

**Issue by 73VW** [grafana/django-saml2-auth#277]
Hello there,

When setting `DEBUG` to `True` in the settings, I expected to see exception debug information in the configured logger.

However, [here](https://github.com/grafana/django-saml2-auth/blob/main/django_saml2_auth/utils.py#L155), the handler tries to access the value of `DEBUG` through `getattr` which works for an object, not a dict. `settings.SAML2_AUTH` is in fact a dict.

Thereby, debug informations are never logged.

I have tried changing:

``` py
        if getattr(settings.SAML2_AUTH, "DEBUG", False):
 ```
 to
 ``` py
        if settings.SAML2_AUTH.get("DEBUG", False)
 ```
 
 And this seems to have fixed the issue but I don't know if it's a version problem or a breaking change in Django. 
  
 Currently using Django 5.0.1 with django-saml-auth 3.12.0
 
 Cheers

**Comment by 73VW** [comment]
I have also tried with Django 4.2.11 and this seems to be the same behaviour.

**Comment by mostafa** [comment]
Hey @73VW,

Good catch! I actually wanted to use `dictor` and not `getattr`, hence the issue. I'll fix it now.

**Comment by 73VW** [comment]
Nice!

Thanks for the fix @mostafa !
