### ISSUE TITLE
SAML support for OpenText NetIQ Access Manager

### ISSUE THREAD

**Issue by Nipuns1999** [grafana/django-saml2-auth#310]
Hi, just wants to know whether this will support integration for OpenText NetIQ Access Manager ( SAML SSO )

**Comment by mostafa** [comment]
Hey @Nipuns1999,

This library support SAML 2.0 standard, and if the software you mention supports that, you can use it. I only tested this integration with Okta and Azure AD SAML SSO. Auth0 and PingIdentity was also tested, but apparently didn't work as expected. However, support for signing requests, assertions and responses are added, which means that those might also support it, but haven't been tested with.
