### ISSUE TITLE
[Question] Manage JWT with djangorestframework_simplejwt

### ISSUE THREAD

**Issue by sgabb** [grafana/django-saml2-auth#34]
Hello,
I was wondering if the JWT used in the library is only the one created specifying the JWT properties in settings.SAML2_AUTH or there would be the possibility to use another manager for the JWT?

For instance, I am using [DRF Simple JWT](https://github.com/jazzband/djangorestframework-simplejwt/blob/master/docs/index.rst) library linked to Django Rest Framework.

Whether this would be a new feature, how would you suggest to plug it in?

Thanks in advance.

**Comment by mostafa** [comment]
@sgabb Currently it only supports [PyJWT](https://github.com/jpadilla/pyjwt). However, I think it's a good idea to make the whole integration configurable, rather than fixed.

I'd be happy to review a PR that introduces this feature.

**Comment by sgabb** [comment]
Allright, I'll see if I could do something!

**Comment by sgabb** [comment]
@mostafa created a [pull request](https://github.com/grafana/django-saml2-auth/pull/35)

Let me know what you think about it!

**Comment by mostafa** [comment]
@sgabb Thanks for your contribution. I'll close this issue and feel free to re-open it if you have any other questions.
