### ISSUE TITLE
Access to saml_response during user creation

### ISSUE THREAD

**Issue by jeremylivingston** [grafana/django-saml2-auth#343]
I am running a multi-tenant application that allows just-in-time provisioning when user accounts don't exist. Part of this requirement is that the user is assigned to the proper tenant once they are created in the system. 

Using the current hooks, `CREATE_USER`, `BEFORE_LOGIN`, and `AFTER_LOGIN`, I don't have access to any of the saml_response where I would derive the tenant that the user should be assigned to (specifically from the Issuer URL).

Is there a way that I can accomplish this with the existing triggers in the library?

**Comment by mostafa** [comment]
Hey @jeremylivingston,

The `token` field and the user attribute mapping exist for this purpose. You can either pass the token or your own list of user attributes to be received in the user assertion. Just let your tenant know that they should populate the said field in their app on the IdP, like Okta. And then, you can retrieve it from the user attributes mapping.

**Comment by jeremylivingston** [comment]
Thanks for the quick response, @mostafa!

I would prefer not to require my users enter a custom attribute if at all possible. Should I use the token method in this case? If so, could you explain how that works exactly? Thanks again!

**Comment by mostafa** [comment]
@jeremylivingston 

You can either: 

1. Use the `TRIGGER.BEFORE_LOGIN` hook function (static) to set up the user based on the domain of their email address.
2. Use the `TRIGGER.GET_USER_ID_FROM_SAML_RESPONSE` hook function (static) to access the SAML Response. In this case, the hook function will receive the decoded, but unvalidated, SAML Response (in XML format) as [`saml_response`](https://github.com/grafana/django-saml2-auth/blob/3781931c620831822873631e374b27aab7325e36/django_saml2_auth/saml.py#L186-L190). If the flow is IdP-initiated, the `user_id` will be `None`, requiring you to extract the `user_id` from the decoded SAML Response. Here I presume that the metadata URL or file that you want to validate the SAML Response against is somehow linked/related to your organization model. To minimize security risks when dealing with unvalidated SAML Responses, I recommend first validating the issuer. This can be found at either of these XML paths (xpaths): `.//{*}Issuer` or `.//{*}Response`. Only after validating the issuer should you extract and validate the `.//{*}NameID` (which represents the email or another user identifier) to match your records. Use ElementTree or your preferred XML library to parse the document.
3. For SP-initiated flows, the user can be mapped based on a set of rules defined by the organization. To handle this, I created a mapping model that links organizations to projects and RBAC. The incoming email is matched against the rules in this model, and if a match is found, I add the user to the organization and set up the project and RBAC for them.

**Comment by jeremylivingston** [comment]
Thanks for the information!

Unfortunately, I can't set the user up based on their email address since we often have customers with the same domain who belong to multiple teams.

I am currently only able to identify the correct team by using the IDP Issuer URL. I am able to do this from the `GET_CUSTOM_METADATA` trigger because it has access to the saml_response. However, there doesn't seem to be a way to pass this to the triggers that happen after user creation. 

I am using the `GET_USER_ID_FROM_SAML_RESPONSE` to identify the email address that is attempting a login, but since this only returns a string, there's no way for me to pass the team from this function to the downstream ones. 

This is only problematic in a scenario when it's a new user that doesn't already have the team on their account. I need to be able to pull the team ID based on the IDP Issuer and join the necessary team after they are successfully authenticated. SP-initiated logins are fine because the user already has to exist; this is only problematic with the IDP-initiated flow with JIT.

Is there a way to accomplish this without requiring that all of our customers pass their team ID as a custom attribute?

**Comment by mostafa** [comment]
@jeremylivingston 

I added a new hook for enriching the user dict with a trigger that receives the `authn_response` (SAML Response). Please test it and provide feedback.

**Comment by mostafa** [comment]
Released in [v3.15.0](https://github.com/grafana/django-saml2-auth/releases/tag/v3.15.0).

**Comment by jeremylivingston** [comment]
Thank you, @mostafa!
