### ISSUE TITLE
Access Token Missing

### ISSUE THREAD

**Issue by tdiaque** [grafana/django-saml2-auth#346]
I am trying to use the get_custom_token_query trigger found in the docs
However, I am getting an exception:
**_[DEBUG] [django_saml2_auth.utils.handle_exception] 'str' object has no attribute 'access_token'_**

How does one ensure the access_token is also passed to the get_custom_token_query trigger?

**Comment by mostafa** [comment]
Hey @tdiaque,

Turn on [debugging](https://github.com/grafana/django-saml2-auth?tab=readme-ov-file#how-to-debug) and please provide a code example.
