### ISSUE TITLE
Feature Request: Pass custom ACS URL

### ISSUE THREAD

**Issue by henryh9n** [grafana/django-saml2-auth#347]
I have a specific use case with my multi-tenant application.
Since we use dynamic routing (with the tenant name in the URL), `utils.get_saml_client()` function fails to get the proper URL for the ACS endpoint. The `get_reverse` finds only the base URL (not the one for tenant).
It happens on this line: https://github.com/grafana/django-saml2-auth/blob/df32f5f05a8261c1cf00f74aedbaf696c4383bda/django_saml2_auth/saml.py#L184

For example, let's say the base ACS URL is `https://example.com/api/acs`. Since we support multiple tenants, `https://example.com/api/tenant-1/acs` and `https://example.com/api/tenant-2/acs` are also valid ACS URLs, however Django will only find the base one (due to the way we set it up).

Would be nice to have a feature to be able to set this URL manually, instead of reversing it.
IMO, ideally we can have 2 ways to do it:
1. **Static**: We set a variable in config which then is used as the ACS URL instead of `reverse()`.
This would be useful when you have some redirects behind the scene.
2. **Dynamic**:  We can pass a hook function that dynamically determines the URL.
Useful when you have dynamic routing and multiple ACS URLs for tenants or other purposes

**Comment by mostafa** [comment]
Hey @henryh9n,

I like the idea the static/dynamic method. We keep backward compatibility while allowing customization of the ACS URL.
