### ISSUE TITLE
Make package available on pypi

### ISSUE THREAD

**Issue by ppease** [grafana/django-saml2-auth#36]
I was wondering if there was a reason this package hasn't been made available on [pypi](https://pypi.org/). This is definitely the most convenient way to be able to download and install python packages.  I would also imagine this would increase the discoverability of the package itself too.

**Comment by mostafa** [comment]
Hey @ppease,

This project was a fork of the original [django-saml2-auth](https://github.com/fangli/django-saml2-auth) by @fangli, but it grew over time and I recently asked GitHub support to unfork it. I want to make it available on PyPI soon, but I should use another name for it, as it might collide with the previous package name.

**Comment by mostafa** [comment]
It is now published at https://pypi.org/project/grafana-django-saml2-auth/.
