### ISSUE TITLE
Mapping groups to staff/superusers

### ISSUE THREAD

**Issue by heydonovan** [grafana/django-saml2-auth#38]
More of a general question than an issue.

We have the implementation working, but this gives everyone superuser status by default:

```
'NEW_USER_PROFILE': {
    'ACTIVE_STATUS': True,
    'STAFF_STATUS': True,
    'SUPERUSER_STATUS': True,
}
```

If we wanted a second group of folks who would be staff, but not superusers, what's the best way to achieve this? I was thinking just creating two groups, but am not sure if cherry-picking permissions to assign to that group gives the same abilities as setting a user to staff/superuser.

**Comment by mostafa** [comment]
Hey @heydonovan,

You can always match group attribute statements with `GROUPS_MAP` and/or use `NEW_USER_PROFILE.USER_GROUPS`, but I haven't used them. I created a custom user to [teams](https://k6.io/docs/cloud/project-and-team-management/saml-sso/#auto-assigning-your-internal-teams-to-k6-projects)/[project](https://k6.io/docs/cloud/project-and-team-management/saml-sso/#assigning-default-project-s-to-newly-provisioned-users) matching system, which works by passing custom user attributes from IdP to the [TRIGGER.BEFORE_LOGIN](https://github.com/grafana/django-saml2-auth/blob/82e63830300a272549e882598d16973953fe4f17/django_saml2_auth/views.py#L123-L125) hook function. There you have all the user attribute statements and the matching system matches based on the attribute name and value and will assign the user to the correct organization and project.

**Comment by mostafa** [comment]
I'll close this due to inactivity. Feel free to re-open it if you still have this issue/question.
