### ISSUE TITLE
Multiple IDP's?

### ISSUE THREAD

**Issue by jeffclay** [grafana/django-saml2-auth#43]
Can this library work with multiple identity providers? If so, can it be more dynamic than hard coding the settings.py file which requires a restart of the django site to take effect? I'm trying to find something that would allow multiple organizations optionally use their IDP with my site by putting their required configs in the web ui.

By the way, thanks for the work on this fork. Very glad to see that there's an updated version supporting modern versions of django.

**Comment by mostafa** [comment]
Hey @jeffclay,

It is multi-tenant and has been tested with Okta, Azure AD SAML SSO, and PingIdentity (Cloud version). You just need to return a list of metadata autoconf URLs to the `TRIGGERS.GET_METADATA_AUTO_CONF_URLS` function and it'll check them against all of the certificates and configurations in those files. Then, for SP-initiated SAML SSO, you can [filter](https://github.com/grafana/django-saml2-auth/blob/82e63830300a272549e882598d16973953fe4f17/django_saml2_auth/views.py#L204) the autoconf URL by the `user_id` passed to your hook function, like this pseudo-code:

```python
def get_metadata_auto_conf_urls(user_id: Optional[str] = None) -> Optional[List[Dict[str, str]]]:
    # Get a list of metadata autoconf URLs filtered by user_id if user_id is not None
    metadata_autoconf_urls = None
    if user_id:
        user: User = User.objects.filter(user_selector_field=user_id).first()
        if user:
            metadata_autoconf_urls = [{"url": user.organization.metadata_autoconf_urls}]
    else:
        # This could be an empty list
        metadata_autoconf_urls = AnyEntity.objects.filter(
            metadata_autoconf_url__isnull=False).values(
                url=models.F('metadata_autoconf_url')))

    return metadata_autoconf_urls if metadata_autoconf_urls else None
```

**Comment by mostafa** [comment]
I'll close this issue. Feel free to reopen it if you have any other questions.
