### ISSUE TITLE
Creating user with custom function

### ISSUE THREAD

**Issue by matiszz** [grafana/django-saml2-auth#54]
Hi, thanks a lot for this library! I was wondering if there is any way of creating a user with my own function. I've seen that the function `create_new_user` creates the `User` with the code:
```
user = user_model.objects.create_user(email, first_name=firstname, last_name=lastname)
```

But my `User` model has attributes `name` and `surname` instead of `first_name` and `last_name`.

It'd be interesting to be able to provide our own function to create it. Is there a way rn? Thanks a lot!

**Comment by mostafa** [comment]
@matiszz 
This feature doesn't exist yet. Feel free to open a PR and introduce it! 🙏 I'd be happy to review it.

**Comment by UraizAli** [comment]
@mostafa 
I have created a PR for this issue can you check it ? if is there any issues related any thing let me know about it. I would love to resolve it.

**Comment by mostafa** [comment]
@matiszz Thanks for raising the issue.
@UraizAli Thanks for your contribution. I fixed the issues on your PR in a separate one and merged it:
- https://github.com/grafana/django-saml2-auth/pull/93
