### ISSUE TITLE
Ability to select URL to authenticate against

### ISSUE THREAD

**Issue by heydonovan** [grafana/django-saml2-auth#80]
Let's say we have 3 different environments, dev, staging and production.

Each has a different URL:

dev.company.com
staging.company.com
company.com

Currently we have 3 different apps for each env. The goal is to only have one, and have the user select which one to use.

With AWS, its one app, and we select which account/role to auth to. For example: [LINK](https://d2908q01vomqb2.cloudfront.net/22d200f8670dbdb3e253a90eee5098477c95c23d/2022/06/09/SAML-SSO-screenshot-sm-v2.png)

Is it possible to achieve the same result? The only difference would be the URL. Maybe the `BEFORE_LOGIN` hook is what would help here? It's like we need some sort of splash page beforehand.

**Comment by mostafa** [comment]
I suppose this is resolved. Feel free to re-open the issue.
