### ISSUE TITLE
Permission Denied, accounts/login/

### ISSUE THREAD

**Issue by ibouzidi** [grafana/django-saml2-auth#91]
Hi, i'm trying to integrate SAML authentication in my Django 3.2 Project but i'm having a permission denied on /accounts/login/  `Sorry, you are not allowed to access this app Error code: 1107 Reason: There was an error processing your request.`

I've tried the package djangosaml2 from IdentityPython and it't worked great, I can login and logout with SAML authentication but with your plugin I can't even acces the login page.

Thanks in advanced.

```
urlpatterns = [
    # django saml auth grafana
    path(r'saml/', include('django_saml2_auth.urls')),
    path(r'accounts/login/', django_saml2_auth.views.signin),
]
```

```
SAML2_AUTH = {
    # Metadata is required, choose either remote url or local file path
    'METADATA_LOCAL_FILE_PATH': [os.path.join(BASE_DIR, 'mylocalfile.xml')],

    'DEBUG': True,  # Send debug information to a log file

    # Optional settings below
    'DEFAULT_NEXT_URL': '/admin',  # Custom target redirect URL after the user get logged in. Default to /admin if not set. This setting will be overwritten if you have parameter ?next= specificed in the login URL.
    'CREATE_USER': True,  # Create a new Django user when a new user logs in. Defaults to True.
    'ATTRIBUTES_MAP': {  # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
        'Email': 'email',
        'UserName': 'username',
        'FirstName': 'first_name',
        'LastName': 'last_name',
    },
    'ASSERTION_URL': 'https://company-name.com/saml/acs',  # Custom URL to validate incoming SAML requests against
    'ENTITY_ID': 'https://company-name.com/',  # Populates the Issuer element in authn request
    'AUTHN_REQUESTS_SIGNED': False, # Require each authentication request to be signed
    'LOGOUT_REQUESTS_SIGNED': False,  # Require each logout request to be signed
    'WANT_ASSERTIONS_SIGNED': False,  # Require each assertion to be signed
    'WANT_RESPONSE_SIGNED': False,  # Require response to be signed
}
```

**Comment by ibouzidi** [comment]
It was the `'METADATA_LOCAL_FILE_PATH': [os.path.join(BASE_DIR, 'mylocalfile.xml')],` I removed the [] like this `'METADATA_LOCAL_FILE_PATH': os.path.join(BASE_DIR, 'mylocalfile.xml'),` and it worked I have my redirection.

**Comment by mostafa** [comment]
Hey @ibouzidi,

I think you have a configuration issue on your IdP app. Try to use SAML-tracer on [Firefox](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/) or [Chrome](https://chrome.google.com/webstore/detail/saml-tracer/mpdajninpobndbfcldcmbpnnbhibjmch?hl=en) to see the request/response with your identity provider.

**Comment by mostafa** [comment]
I'll close this ticket. Feel free to re-open it if you still have issues.
